import { max } from "moment-timezone";

// --- STYLES (Web Version using JS Objects) ---
const styles = {
  appContainer: {
    margin: "0 auto",
    maxWidth: "40rem",
    height: "100vh",
    backgroundColor: "#1c1917",
    fontFamily: "sans-serif",
    overflow: "auto",
  },
  container: {
    minWidth: "100%",
    height: "100vh",
    backgroundColor: "#1c1917",
    paddingTop: 40,
    boxSizing: "border-box",
    overflowY: "auto",
  },
  scrollContent: {
    width: "100%",
    padding: 20,
    paddingBottom: 100,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#f0f9ff",
    marginBottom: 10,
    paddingLeft: 16,
    paddingRight: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#e5e7eb",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: "#a1a1aa",
    marginBottom: 20,
  },
  button: {
    backgroundColor: "#2563eb",
    padding: "15px 0",
    borderRadius: 12,
    textAlign: "center",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0,0,0,0.25)",
    transition: "background-color 0.2s",
  },
  disabledButton: {
    backgroundColor: "#4b5563",
    cursor: "not-allowed",
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    margin: 0,
  },
  smallButton: {
    padding: "8px 12px",
  },
  smallButtonText: {
    fontSize: 14,
    fontWeight: "500",
  },
  card: {
    backgroundColor: "#262626",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    border: "1px solid #404040",
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#d4d4d8",
    marginBottom: 15,
  },
  input: {
    backgroundColor: "#1c1917",
    color: "#e5e7eb",
    padding: 15,
    borderRadius: 10,
    fontSize: 16,
    marginBottom: 15,
    border: "1px solid #52525b",
    width: "calc(100% - 32px)",
  },
  label: {
    fontSize: 16,
    color: "#a1a1aa",
    marginBottom: 8,
  },
  onboardingContainer: {
    flex: 1,
    paddingTop: 40,
    backgroundImage: "linear-gradient(to bottom, #1e3a8a, #1c1917)",
    color: "white",
    textAlign: "center",
  },
  onboardingTitle: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
    marginBottom: 10,
  },
  onboardingSubtitle: {
    fontSize: 18,
    color: "#dbeafe",
    textAlign: "center",
    marginBottom: 40,
  },
  onboardingText: {
    fontSize: 16,
    color: "#d4d4d8",
    marginBottom: 10,
    lineHeight: 1.5,
    textAlign: "left",
  },
  walletCard: {
    borderRadius: 20,
    padding: 25,
    marginBottom: 20,
    textAlign: "center",
    backgroundImage: "linear-gradient(to bottom, #3b82f6, #1d4ed8)",
  },
  walletLabel: {
    fontSize: 18,
    color: "#dbeafe",
  },
  walletBalance: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#fff",
  },
  suggestionCard: {
    backgroundColor: "#1e3a8a",
    borderColor: "#3b82f6",
  },
  suggestionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#dbeafe",
    marginBottom: 5,
  },
  suggestionMessage: {
    fontSize: 16,
    color: "#bfdbfe",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  emptyText: {
    textAlign: "center",
    color: "#a1a1aa",
    fontSize: 16,
    marginTop: 20,
    padding: 20,
  },
  habitItem: {
    display: "flex",
    alignItems: "center",
    padding: 12,
  },
  habitTrend: {
    fontSize: 24,
    marginRight: 15,
  },
  habitName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#e5e7eb",
  },
  habitArea: {
    fontSize: 14,
    color: "#a1a1aa",
  },
  habitReward: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#4ade80",
  },
  habitPenalty: {
    fontSize: 14,
    color: "#f87171",
  },
  analysisText: {
    marginTop: 15,
    fontSize: 14,
    color: "#93c5fd",
    fontStyle: "italic",
    textAlign: "center",
    whiteSpace: "normal",
    lineHeight: 1.6,
    backgroundColor: "rgba(23, 37, 84, 0.5)",
    padding: "10px",
    borderRadius: "8px",
  },
  costContainer: {
    backgroundColor: "rgba(23, 37, 84, 0.5)",
    padding: "10px",
    borderRadius: "8px",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 5,
  },
  costLabel: {
    color: "#dbeafe",
    fontSize: 16,
    fontWeight: "600",
  },
  costSublabel: {
    color: "#93c5fd",
    fontSize: 12,
  },
  errorText: {
    color: "#fca5a5",
    textAlign: "center",
    fontSize: 14,
    marginTop: 10,
  },
  trackerItem: {},
  trackerActions: {
    display: "flex",
  },
  actionButton: {
    width: 30,
    height: 30,
    borderRadius: 25,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: "0 10px",
    border: "none",
    cursor: "pointer",
  },
  actionButtonText: {
    fontSize: 18,
    color: "#1c1917",
    fontWeight: "bold",
  },
  completeButton: {
    backgroundColor: "#4ade80",
  },
  missButton: {
    backgroundColor: "#f87171",
  },
  summaryContainer: {
    display: "flex",
    justifyContent: "space-around",
  },
  summaryBox: {
    textAlign: "center",
  },
  summaryLabel: {
    fontSize: 16,
    color: "#a1a1aa",
  },
  summaryValue: {
    fontSize: 24,
    fontWeight: "bold",
    marginTop: 5,
  },
  settingDescription: {
    fontSize: 14,
    color: "#a1a1aa",
    marginTop: 10,
    lineHeight: 1.4,
  },
  navigation: {
    display: "flex",
    position: "sticky",
    bottom: 0,
    zIndex: "99",
    height: 65,
    backgroundColor: "#262626",
    borderTop: "1px solid #404040",
    justifyContent: "space-around",
    alignItems: "center",
  },
  navButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    width: "100px",
    padding: "10px 0px",
  },
  navText: {
    fontSize: 28,
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    zIndex: 1000,
  },
  modalContainer: {
    width: "90%",
    maxWidth: 500,
    backgroundColor: "#262626",
    borderRadius: 16,
    padding: 20,
    border: "1px solid #404040",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#e5e7eb",
  },
  modalCloseButton: {
    fontSize: 18,
    color: "#a1a1aa",
    fontWeight: "bold",
    background: "none",
    border: "none",
    cursor: "pointer",
  },
  modalText: {
    fontSize: 16,
    color: "#d4d4d8",
    lineHeight: 1.5,
  },
  // Chart Styles
  pieChart: {
    width: 150,
    height: 150,
    borderRadius: "50%",
    border: "1px solid #404040",
  },
  legendContainer: {
    marginTop: 20,
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    margin: "0 10px 5px",
  },
  legendColorBox: {
    width: 14,
    height: 14,
    marginRight: 8,
    borderRadius: 3,
  },
  legendText: {
    color: "#d4d4d8",
    fontSize: 14,
  },
  barChartContainer: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "flex-end",
    height: 200,
    borderLeft: "1px solid #52525b",
    borderBottom: "1px solid #52525b",
    padding: "10px 0",
  },
  barWrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    height: "100%",
    justifyContent: "flex-end",
    flex: 1,
  },
  bar: {
    width: "50%",
    borderRadius: "4px 4px 0 0",
  },
  barLabel: {
    color: "#a1a1aa",
    fontSize: 12,
    marginTop: 5,
  },
  // Calendar Styles
  calendarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: "5px",
  },
  calendarHeader: {
    textAlign: "center",
    fontWeight: "bold",
    color: "#a1a1aa",
    fontSize: 14,
  },
  calendarDay: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 35,
    borderRadius: 6,
    backgroundColor: "#404040",
    color: "#a1a1aa",
  },
  calendarDayComplete: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 35,
    borderRadius: 6,
    backgroundColor: "#22c55e",
    color: "#14532d",
    fontWeight: "bold",
  },
  calendarDayMissed: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 35,
    borderRadius: 6,
    backgroundColor: "#ef4444",
    color: "#7f1d1d",
    fontWeight: "bold",
  },
};

export default styles;
